name: pytest
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8] # 3.6, 3.7, 3.8 - restricted because of Colab python version
        poetry-version: [1.1.2]
        os: [ubuntu-latest] # macos-latest, windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies and run pytest
        run: |
          poetry install
          poetry run pytest
